
_target_: csi_catm.models.base_model.BaseModel
visual_backbone: 
  _target_: csi_catm.models.resnet.Resnet
  cfg: ${resnet_cfg}
  ckpt: ${resnet_ckpt}
  drop_prob: 0.5
sequence_backbone:
  _target_: csi_catm.models.bilstm.BiLSTMLayer
  input_size: 512
  hidden_size: 512
  num_layers: 2
  bidirectional: True
  dropout: 0.5
header:
  _target_: torch.nn.Linear
  in_features: 512
  out_features: 8
  
